name: Build iOS for TrollStore

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    # Chuyển về macos-13 để tránh bộ SDK 26.0 bị lỗi
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.100'

    - name: Install iOS Workload
      run: dotnet workload install maui-ios

    - name: Build IPA
      # Thêm các tham số ép buộc ngay trong lệnh build
      run: |
        PROJECT_FILE=$(find . -name "*.csproj" -not -path "*/obj/*" -not -path "*/bin/*" | head -n 1)
        dotnet publish "$PROJECT_FILE" -f net9.0-ios -c Release -p:BuildIpa=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="-" -p:CodesignProvision="" -p:_SuppressXcodeVersionCheck=true -p:_XcodeVersionCheckDone=true
      
    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TKB-App-IPA
        path: '**/publish/*.ipa'
